name: Slack Manifest Deploy

on:
  push:
    paths:
      - 'manifest.json'

jobs:
  create-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create Slack App from Manifest
        env:
          SLACK_ADMIN_TOKEN: ${{ secrets.SLACK_ADMIN_TOKEN }}
        run: |
          echo "Reading manifest.json..."
          MANIFEST_CONTENT=$(cat manifest.json)
          
          echo "Creating Slack app..."
          curl -X POST "https://slack.com/api/apps.manifest.create" \
            -H "Authorization: Bearer $SLACK_ADMIN_TOKEN" \
            -H "Content-Type: application/json; charset=utf-8" \
            -d "{\"manifest\": $MANIFEST_CONTENT}"
